cerner/cerner_splunk

- recipes/_configure_authentication.rb
- vagrant_repo/data_bags/cerner_splunk/authnz-vagrant.json
This PR is for fixing Issue #3. 
There are two other places where the splat operator is in use, but in these cases, using the splat seems to be the correct behavior:
* [libraries/splunk_app.rb](https://github.com/cerner/cerner_splunk/blob/1.7.0/libraries/splunk_app.rb#L139) - role will either be a String or an Array 
* [vagrant_repo/cookbooks/cerner_splunk_test/templates/default/access.log.erb](https://github.com/cerner/cerner_splunk/blob/1.7.0/vagrant_repo/cookbooks/cerner_splunk_test/templates/default/access.log.erb) - This is an expansion of an explicit range in the test cookbook.
> Fixes #3 - Fix splat operator in authorize.conf generation

- Vagrantfile
- docs/databags.md
- libraries/conf.rb
- libraries/splunk_app.rb
- libraries/tarball.rb
- recipes/_configure_apps.rb
- vagrant_repo/apps/my_app/default/app.conf
- vagrant_repo/apps/my_app/default/data/ui/nav/default.xml
- vagrant_repo/apps/my_app/default/data/ui/views/lorem_ipsum.xml
- vagrant_repo/apps/my_app/metadata/default.meta
- vagrant_repo/data_bags/cerner_splunk/apps-vagrant.json
Implementation of #37. This was quite the adventure. But this gives us the ability to install apps from .tar.gz files (and .spl, but .spl is just a renamed .tar.gz). We'll need a new enhancement / issue if we want to install apps from .zip files as well. (In the past few days I've seen a number zip files with all kinds of formats.)
Please review and be harsh! Question everything!
> Fixes #37 - Install apps via tarballs 

- Gemfile
- recipes/_configure_apps.rb
- spec/unit/libraries/splunk_app_spec.rb
- spec/unit/recipes/_configure_apps_spec.rb
- spec/unit/spec_helper.rb
Fix for #47. Simply add a little indirection and voila. Also a very simple chefspec test as a first step. Would like to start doing more of these.
> Fixes #47 - _configure_apps runs when there is no configured cluster databag

- libraries/splunk_template.rb
- libraries/tarball.rb
- recipes/cluster_master.rb
To get this in, here are the fixes for windows installation of apps (i.e. do not chown on windows), and the fix for cluster apps (i.e. actually respect the download attributes)
There's also a rubocop update as well.
> Fixes #64 - Tweaks to packaged app installation

- recipes/_install.rb
Fixes #68 by creating the directory after the package (and subsequently the user) are installed.
> Fixes #68 - moving directory creation to after package install

- recipes/license_server.rb
Fixes #72 Apparently we missed adding the sensitive flag to the license resource. This will ensure that as new licenses are added we don't log out the contents.
> Fixes #72 - Add Sensitive flag to License resource

- .travis.yml
- Gemfile
- recipes/_install.rb
* Fixing the Rubocop failures from #76
* Bumping minor versions in Gemfile to match the latest of each
* Updating to the [new Travis CI architecture](http://docs.travis-ci.com/user/migrating-from-legacy/)
* Bumping the ruby version to match the version shipped with omnibus chef 12.4.1
Proposed incrementing fix version for the cookbook with the merge of these changes.
> Rubocop and Travis Updates

- Vagrantfile
- docs/vagrant.md
After #76 while working on the upgrade I realized a few things. One that Opentable Windows VM is missing a rather important line (Requested update from OpenTable here: https://twitter.com/acharlieh/status/629690576024137728 )
While I was at it, I realized that the default case shouldn't be to rebuild the apps all the time, so I added an ENV switch for it.
As it's Vagrant changes only, no version increment warranted.
> Further Vagrantfile Fixes

- recipes/_install.rb
Fixes #80. Instead of subscribing to a change, we're just going to ensure this file exists by touching it, but not if it already exists.
We probably should adopt this pattern with other resources too eventually.
Proposed: fix version increment as this is a bug.
> Fixes #80 Ensure .ui_login file is always created

- Vagrantfile
Doesn't actually do anything anymore, so we should remove it. 
Prior to #76, the Virtualbox images that we were using had a too small opt partition on vg00, which caused [Splunk's settings on free disk space](http://docs.splunk.com/Documentation/Splunk/6.2.5/Indexer/Setlimitsondiskusage#Set_minimum_free_disk_space) to kick off so we needed to resize it. The images we're using since that pull request, don't have a vg00, therefore this command is doing nothing but take a bit of time and spit out an error message which is ignored as we happily scoot along. 
Proposed no version increment as this is a Vagrantfile change only.
> More Vagrant Tweaks - Resizing of vg00

- Vagrantfile
Updated to the new bento namespace, which required an update to the 6.7 box as the 6.5 and 6.6 boxes are not present.
> Fixes #87 - Update Vagrantfile to point to new bento box location

- libraries/recipe.rb
- providers/forwarder_monitors.rb
- recipes/_configure_alerts.rb
- recipes/_configure_apps.rb
- recipes/_configure_authentication.rb
- recipes/_configure_indexes.rb
- recipes/_configure_inputs.rb
- recipes/_configure_outputs.rb
- recipes/_configure_roles.rb
- recipes/_configure_ui.rb
- recipes/_install.rb
- recipes/_start.rb
- recipes/_user_management.rb
- recipes/license_server.rb
- vagrant_repo/cookbooks/cerner_splunk_test/providers/lwrp.rb
- vagrant_repo/cookbooks/cerner_splunk_test/recipes/default.rb
- vagrant_repo/cookbooks/cerner_splunk_test/resources/lwrp.rb
Fixes #18
Essentially we are implementing the design developed with https://github.com/cerner/cerner_splunk/pull/22#issuecomment-124629692 
But we create a marker file, and setup a delayed restart at the beginning. Every time we make a change, we touch the marker file. If we successfully start or restart, we delete the marker file.
Proposing a Minor version increment as while it fixes the expected state, it feels broader than just a simple fix.
> Fixes #18 - Use a marker file for restart notifications

- libraries/splunk_app.rb
Fixes #85 
This seemed to be in agreement with the treatment of the empty string in the same method. Other solutions are possible.
> Check for empty hashes as well

- docs/vagrant.md
The vagrant doc file had out of date artifact versions, updated to match the current defaults in `attributes/_install.rb`.
> Update splunk artifacts to 6.2.5 in vagrant doc

- Berksfile.lock
- Gemfile
- metadata.rb
- recipes/_install.rb
- recipes/_restart_marker.rb
- recipes/_start.rb
- spec/unit/recipes/_restart_marker_spec.rb
- spec/unit/recipes/_start_spec.rb
Updated _start recipe to edit the splunk init.d script with a ulimit command if needed.
> Fixes #96. Add ulimit command to init.d script to ensure ulimits are applied

- docs/databags.md
- libraries/matchers.rb
- recipes/_configure_indexes.rb
- spec/unit/recipes/_configure_indexes_spec.rb
- spec/unit/recipes/_start_spec.rb
- spec/unit/spec_helper.rb
- vagrant_repo/data_bags/cerner_splunk/indexes-vagrant.json
This allows a convenient way to specify the base volume for a given index.  Otherwise you would have to specify the coldPath and homePath for each index individually within the indexes data bag.  I originally considered putting the volume within the config/\<index_name\> location but then that hash would no longer match the raw indexes.conf stanza anymore.  So I opted to put it in the flags, although I know those were originally meant to be boolean only.  I'm open to suggestion on a better place to put the volume specification for an index in the data bag if you want to keep flags as only boolean attributes.
> Allow convenient specification of volumes for index storage locations

- metadata.rb
These weren't added until Chef 12, so we need to have them be optional for as long as we support Chef 11.
They were introduced with: chef/chef@fe6d60f7a9456a97457f37a20729e366a714f428
Proposing no version change on merge (as it's nothing to do with the cookbook itself, just the metadata of it.
> Make the source and issues url optional.

- Gemfile
- attributes/_install.rb
- docs/attributes.md
- docs/vagrant.md
- spec/unit/recipes/_install_spec.rb
- spec/unit/spec_helper.rb
* Update Splunk version attributes to be specific to Splunk 6.3.3
* Added ChefSpec tests for _install.rb recipe
Tested upgrade path from previous version by provisioning vagrant before and after switching the version attributes.
> Splunk 6.3.3 Upgrade

- Vagrantfile
This PR is to fix #110 where the chef-dk install fails when attempting to run vagrant. I based the new install command on the [chef-dk's readme installation instructions](https://github.com/chef/chef-dk#linux-and-osx)
> Fix chef-dk install command in Vagrantfile

- Vagrantfile
- docs/attributes.md
- docs/databags.md
- docs/vagrant.md
- libraries/unit_converter.rb
- recipes/_configure_server.rb
- recipes/license_server.rb
- spec/unit/libraries/unit_converter_spec.rb
- vagrant_repo/cookbooks/cerner_splunk_test/recipes/configure_guids.rb
- vagrant_repo/cookbooks/cerner_splunk_test/templates/default/instance.cfg.erb
- vagrant_repo/data_bags/cerner_splunk/license-vagrant.json
- vagrant_repo/environments/splunk_license.json
This enhancement allows better management of license pools. Earlier all the indexers went into the same pool(auto_generated_pool) which had the max quota. You will now be able to specify which indexer goes into which pools and set the license quota for each pool.
> Enable managing license pools

- .travis.yml
- Berksfile
- Gemfile
- README.md
- metadata.rb
Fixes #117 also includes the commit from #114 that fixes #112
We'll bump the version number to 2.0 as part of this, so any features merged after this point are not guaranteed to work necessarily on Chef 11
> Drop Chef 11 support

- attributes/_install.rb
- docs/attributes.md
- docs/vagrant.md
- spec/unit/recipes/_install_spec.rb
Update default Splunk version attributes to install Splunk 6.3.4.
Also tested upgrade path from previous version by provisioning vagrant before and after switching the version attributes.
> Splunk 6.3.4

- Vagrantfile
- docs/databags.md
- libraries/matchers.rb
- libraries/splunk_app.rb
- recipes/_configure_apps.rb
- spec/unit/recipes/_configure_apps_spec.rb
- vagrant_repo/data_bags/cerner_splunk/apps-vagrant.json
- vagrant_repo/files/lookups/index-owners.csv
- vagrant_repo/files/lookups/test.txt
This PR is to enhance the splunk_app resource to support lookup specification. 
The use case is that we need to deploy a lookup file to the license server so that we can have a index-ownership lookup which can potentially help in notifying the index owners about any over indexing that might lead to license violation. This enhancement will help us source control the contents of the lookup file.
> splunk_app resource to support lookup specification

- libraries/rc4.rb
- libraries/splunk_password.rb
- libraries/splunk_template.rb
- recipes/_configure_authentication.rb
- recipes/_configure_server.rb
- recipes/_install.rb
- spec/unit/libraries/splunk_password_spec.rb
- spec/unit/recipes/_install_spec.rb
This enhancement will support writing Splunk encrypted passwords in the config files.
Splunk encrypts passwords written in the config files. This causes Chef to detect a password which is different from what was written before causing Splunk to restart (to reflect the change). Writing the encrypted passwords into the conf file will prevent this restart from happening every time.
> Support encrypting passwords when written to conf files

- docs/databags.md
- recipes/_configure_indexes.rb
- recipes/_configure_server.rb
- spec/unit/recipes/_configure_indexes_spec.rb
- spec/unit/recipes/heavy_forwarder_spec.rb
- vagrant_repo/data_bags/cerner_splunk/cluster-vagrant.json
- vagrant_repo/data_bags/cerner_splunk/indexes-vagrant.json
To make the calculation of maxTotalDataSizeMB a little more intuitive, this allows a value in MB per day to be specified in the data bag and the maxTotal index size will be calculated based on that value along with the other cluster size values.
> Allow specification of index size in MB per day

- libraries/rc4.rb
- spec/unit/libraries/splunk_password_spec.rb
PR to fix the issue identified in https://github.com/cerner/cerner_splunk/issues/125.
Reading about character encoding, this seems to be the best way to fix issues with any type of character encoding (force_encoding to binary and then use the ASCII vs just taking the bytes). There is also PR open by someone to the Ruby-RC4 project to fix it.
This update fixed the issue with sslConfig and pass4SymmKey passwords that I was experiencing while working on https://github.com/cerner/cerner_splunk/pull/124.
> Fix character encoding issues during RC4 encryption

- .rubocop.yml
Rubocop's release on Monday introduced an enforcement of style of variables with numbers in their names... bbatsov/rubocop#3167 which promptly caused the [latest stable merge to fail](https://travis-ci.org/cerner/cerner_splunk/builds/161359413).
IMHO such an enforcement beyond the simplest of code requires too much parsing of semantic meaning to be able to implement properly in a quick cop. Pick a style and try to sensibly enforce it with variable names referencing names of things or multiple named indexes `tls1_1`, `sha256`, `PKCS1-v1_5` or `TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384` (normal comes closest, but even still there are cracks... )
So remember ![only you can kill it with fire](http://i3.kym-cdn.com/entries/icons/facebook/000/000/261/kill_it_with_fire_square.jpg)
> Take rubocop back down a peg

- Berksfile
- Vagrantfile
- attributes/_configure.rb
- attributes/_install.rb
- docs/attributes.md
- docs/vagrant.md
- recipes/_configure_server.rb
- spec/unit/recipes/_install_spec.rb
This PR introduces the following changes.
1. Upgrades Splunk to 6.5.2. The upgrade was tested using vagrant. It was noticed during testing that on all instances except license server where master_uri is set to _self_ need to have active_group set to _Trial_ to leverage the enterprise(trial) features. 
2. Updates the _configure_server recipe so that the heavy forwarder now points to the license server so that it can leverage the enterprise features.
> Splunk 6.5.2 upgrade and point heavy forwarder to license master.

- attributes/_install.rb
- docs/attributes.md
- docs/vagrant.md
- spec/unit/recipes/_install_spec.rb
Yes we just tagged, to get onto Splunk 6.5.2, but 6.5.3 was released and has security patches to it.
For more information see: http://www.splunk.com/view/SP-CAAAPZ3
> Splunk 6.5.3

- Vagrantfile
- libraries/splunk_password.rb
- recipes/_configure_server.rb
With the update to 6.5.x, apparently `sslKeysfilePassword` in server.conf was deprecated in favor of `sslPassword`
> Update to use sslPassword instead of sslKeysfilePassword

- Gemfile
- docs/attributes.md
- libraries/lwrp.rb
- providers/forwarder_monitors.rb
- recipes/_configure.rb
- recipes/_configure_inputs.rb
- spec/unit/recipes/_configure_spec.rb
When we have all the configs (including the outputs.conf) packaged in an app and installed on a fowarder, we don't have to again specify the cluster databag for the forwarder. This PR updates the _configure recipe to log a warning if no cluster data bags are configured rather than throw an error.
@acharlieh also mentioned that we could remove the index check validation in this PR since it doesn't add much value today.
> Remove index validation and cluster data bag validation for forwarders

- LICENSE
- NOTICE
- README.md
Our application of the Apache License 2.0 was not correct ([doc](https://www.apache.org/dev/apply-license.html)). This PR fixes this.
> Fix licensing artifacts to reflect the Apache License 2.0.

- Vagrantfile
- docs/databags.md
- libraries/conf_template.rb
- libraries/outputs.rb
- recipes/_configure_inputs.rb
- recipes/_configure_server.rb
- spec/unit/recipes/_configure_outputs_spec.rb
- spec/unit/spec_helper.rb
- vagrant_repo/data_bags/cerner_splunk/cluster-indexer-discovery.json
- vagrant_repo/data_bags/cerner_splunk/cluster-vagrant.json
- vagrant_repo/environments/splunk_cluster_master.json
- vagrant_repo/environments/splunk_standalone.json
This PR introduces support for indexer discovery.  http://docs.splunk.com/Documentation/Splunk/6.6.0/Indexer/indexerdiscovery
There are ChefSpecs included in this PR. Also, the vagrant set up is now updated so that the forwarder talks to the peers in the clustered setup using indexer discovery and to the standalone instance in the traditional way (where we list the peer IPs using the `servers` attribute in the `tcpout` stanza).
> Add support for indexer discovery

- docs/attributes.md
- docs/vagrant.md
- libraries/splunk_password.rb
- recipes/_configure_server.rb
- recipes/_generate_password.rb
- spec/unit/libraries/splunk_password_spec.rb
- vagrant_repo/data_bags/cerner_splunk/cluster-vagrant.json
- vagrant_repo/data_bags/cerner_splunk/standalone_passwords.json
- vagrant_repo/environments/splunk_standalone.json
The cookbook has partial support for configuring the pass4SymmKey, but it was missing for certain node types.  This adds in support for setting it on cluster masters, cluster slaves and shc deployers.
In addition, previously there was no way to specify the admin password. It was always randomly generated and reset on every chef run.  This adds in the ability to set the admin password to a specific value via data bag.
> Allow config for admin password and pass4SymmKey for all node types

- .travis.yml
- Gemfile
- attributes/_install.rb
- docs/attributes.md
- spec/unit/recipes/_install_spec.rb
Why?
I am submitting this PR because Splunk 7.0.1 is having issues with indexer clusters and Charlie recommended that I upgrade to 7.0.3.
> Update Splunk to 7.0.3

- Vagrantfile
- attributes/_configure.rb
Vagrant provisioning is broken in master since it installs the latest chefdk with Chef 14 on it.  This cookbook hasn't been updated to be compatible yet, and the the chef node fails to provision.  Chefdk 2.5.3 is the last version that still works, even though it embeds Chef 13.
We missed removing the default index_checks_fail attribute in #154.
> Minor cleanup

- attributes/_install.rb
- docs/attributes.md
- metadata.rb
- recipes/shc_deployer.rb
- recipes/shc_search_head.rb
- spec/unit/recipes/_install_spec.rb
- spec/unit/recipes/shc_deployer_spec.rb
- spec/unit/recipes/shc_search_head_spec.rb
>Updated new version of Splunk 7.2.6. 
>I have added the "is_cloud" attribute for Search head clustering as the shc_member IP's to be provided in data-bag for SHC are not available for cloud instances initially.
> adding new attribute for  Search Head Cluster in cloud

- attributes/_configure.rb
- docs/attributes.md
- metadata.rb
- recipes/_start.rb
I am creating an attribute so that we can configure more splunk enable boot-start arguments while still leaving what was there as the default attribute.
> adding attribute for boot start arguments

- .travis.yml
- Gemfile
- attributes/_configure.rb
- metadata.rb
- recipes/_install.rb
- recipes/_start.rb
- spec/unit/recipes/_configure_shc_alerts_spec.rb
- spec/unit/recipes/_install_spec.rb
- spec/unit/recipes/_start_spec.rb
- vagrant_repo/data_bags/cerner_splunk/alerts-vagrant.json
Updated to follow the latest documentation:
* https://docs.splunk.com/Documentation/Splunk/latest/Admin/ConfigureSplunktostartatboottime#Enable_boot-start_as_a_non-root_user
* https://docs.splunk.com/Documentation/Splunk/7.3.1/Admin/RunSplunkassystemdservice#Configure_systemd_using_enable_boot-start
While I was testing, I ran into a number of other largely unrelated issues with the vagrant setup running under systemd.  Also, the windows install has been completely broken for some time, so I fixed that too.
> Update boot start scripts

- attributes/_install.rb
- docs/attributes.md
- metadata.rb
- spec/unit/recipes/_install_spec.rb
Update default to latest version, 7.3.1.
> Update Splunk to 7.3.1

- .travis.yml
- Gemfile
- metadata.rb
Update linting dependencies after the release.  Also had to add in a version constraint for faraday since the ruby 2.3.1 build is now failing after the recent release of faraday 0.16.x.
On a minor note, I realized Chef 14.13.11 ships with ruby 2.5.5 embedded, so updated travis to build with that instead of 2.5.1.
> Update dependencies and bump version post-release

- libraries/splunk_app.rb
- metadata.rb
File.rename does not handle copying files between filesystems. So on certain setups, apps would fail to install with the following error:
```
Errno::EXDEV
------------
Invalid cross-device link @ rb_file_s_rename - (/tmp/kitchen/cache/test_app, /opt/splunk/etc/apps/test_app)
```
FileUtils.mv handles this and performs a copy/delete operation instead when this error occurs.
https://ruby-doc.org/stdlib-2.5.5/libdoc/fileutils/rdoc/FileUtils.html#method-c-mv
> Fix splunk_app to handle moving files between filesystems

- Vagrantfile
- attributes/_install.rb
- docs/attributes.md
- spec/cookbooks/cerner_splunk_test/recipes/install_libarchive.rb
- spec/unit/recipes/_install_spec.rb
Mostly just updating Splunk to the latest release in the 7.x line.  However, when I tested all the vagrant boxes several of them had been missed in my previous commit to add support for mixlib-archive, so I went ahead and included those fixes in here too.
> Update Splunk to 7.3.2

- Vagrantfile
- attributes/_install.rb
- docs/attributes.md
- metadata.rb
- spec/unit/recipes/_install_spec.rb
Based on the information in https://docs.splunk.com/Documentation/Splunk/8.0.0/ReleaseNotes/FixDatetimexml2020, we should bump the default version to 7.3.3 to include the date time patch.
Also increased the vagrant setup to use the latest centos (7.7) while I was in here.
> Update default Splunk version to 7.3.3

- .travis.yml
- Gemfile
- Vagrantfile
- metadata.rb
* Adding Support for Chef-client 15
* This cookbook's chef-client restriction is impacting other cookbooks that leverage it. The latest Chef-client version cannot be leveraged by any cookbooks that consume share a run-list with the cerner_splunk cookbook
* We would like to lift this restriction so that consuming cookbooks will be free to leverage the latest chef-client version
@gravesb please review and test it locally.
> Add Support for Chef-client 15

- .rubocop.yml
- Gemfile
- README.md
- libraries/authentication.rb
- libraries/conf_template.rb
- libraries/databag.rb
- libraries/lwrp.rb
- libraries/passive_sensitive.rb
- libraries/recipe_utils.rb
- libraries/roles.rb
- libraries/splunk_app.rb
- metadata.rb
- spec/unit/libraries/recipe_utils_spec.rb
- spec/unit/recipes/_install_spec.rb
Update linting and testing dependencies after the release.  The foodcritic issue still wasn't resolved so I applied the workaround to rename the recipe.rb library file. The cucumber issue was resolved though, so we no longer needed that version pin.
> Post release gem updates, fix lint

- Vagrantfile
- docs/attributes.md
- metadata.rb
- recipes/_install.rb
- spec/cookbooks/cerner_splunk_test/recipes/install_libarchive.rb
- spec/unit/recipes/_install_spec.rb
- spec/unit/recipes/_start_spec.rb
- vagrant_repo/environments/splunk_standalone.json
It turns out, we were requiring users to configure a value that was never actually used.  See the comments inline for additional information.
> Remove unnecessary windows_password configs

- Vagrantfile
- metadata.rb
Turns out, I mostly just needed to upgrade to a newer version of vagrant in order to get things working on the windows box.  They made a fix in 2.2.5 around detecting the version of chef that was installed.  But in looking at that, I realized vagrant supports installing a specified version of chef out of the box. So the vagrant-omnibus plugin is completely unnecessary.  I'm guessing maybe back in the day when it was added, vagrant didn't support the chef install?
https://www.vagrantup.com/docs/provisioning/chef_common.html
> Removed deprecated vagrant-omnibus plugin dependency

- .travis.yml
- CONTRIBUTING.md
- docs/contributing.md
- libraries/passive_sensitive.rb
I already created a new branch named main per the instructions here:
https://www.hanselman.com/blog/EasilyRenameYourGitDefaultBranchFromMasterToMain.aspx
This is just to cleanup any remaining documentation references to it.
> Rename master branch to main

- .travis.yml
- Gemfile
- README.md
- Vagrantfile
- metadata.rb
- providers/sh_cluster.rb
We are doing internal uplift for chef-client for all cookbooks. We want to support latest two chef-client version which would be 15.x & 16.x. This PR lifts the upper limit so consumer can run it with 16. 
Please review. @acharlieh @gravesb Let me know if I am missing anything. I tested all vagrant suites locally. They converged successfully.
> Loosening up upper limit for chef-client

- libraries/recipe_utils.rb
- libraries/splunk_app.rb
- metadata.rb
- spec/unit/libraries/recipe_utils_spec.rb
- vagrant_repo/environments/splunk_standalone.json
When specifying multiple clusters in the splunk/config/clusters array, only the first element would have the multi-site attributes loaded properly.  If a multi-site cluster was in any other position in the array, it would essentially be ignored and nothing would be added to server.conf to use it as a search peer.  This corrects the issue and adds some unit tests around it.
> Fix issue with configuring multiple multi-site clusters for searching

- libraries/splunk_app.rb
- metadata.rb
When running on Chef Client 15.13.8 and above, the following deprecation warning is present:
```
Resource chef_vault_secret needs `provides :chef_vault_secret` in addition to `resource_name :chef_vault_secret` declaration
Please see https://docs.chef.io/deprecations_resource_name_without_provides/ for further details and information on how to correct this problem.
```
This has been corrected in chef-vault 4.0.3, so we need to open up the version restriction to allow for newer versions of chef-vault to be used with cerner_splunk.
I didn't put an upper limit because I don't believe the chef-vault cookbook will be getting much more development, if any, because it is now included in the [Chef Infra client package as of Chef 16](https://docs.chef.io/release_notes/#chef-vault-functionality-out-o …
> Loosen version restriction on chef-vault

- .rubocop.yml
- Gemfile
- metadata.rb
- spec/unit/recipes/_configure_secret_spec.rb
- spec/unit/recipes/_install_spec.rb
- spec/unit/recipes/_migrate_forwarder_spec.rb
Update linting and testing dependencies after the release.
We'll likely drop support for ruby 2.3 in the very near future, but I didn't want to mix that in here.
> Post-release gem updates, fixed new lint and warnings

- attributes/_install.rb
- docs/attributes.md
- metadata.rb
- spec/unit/recipes/_install_spec.rb
Since 8.1.0 is out, seems like a good time to bump the default Splunk version to the latest 8.0.x.
> Upgrade default Splunk version to 8.0.7

- .rubocop.yml
- .travis.yml
- Gemfile
- README.md
- libraries/splunk_app.rb
- metadata.rb
Fixes #230.
Per https://github.com/sous-chefs/line/blob/master/CHANGELOG.md#210---2018-09-28 it appears filter_lines was not added until 2.1.0 so that should be the minimum declared version.
Edit: The ruby 2.3 travis test was failing, so rather than fixing it I'm removing support and testing for some old EOL ruby and chef versions.  Since that's a more impactful change, I updated the PR title accordingly.
> Drop support for EOL ruby and chef versions

- attributes/_install.rb
- docs/attributes.md
- metadata.rb
- spec/unit/recipes/_install_spec.rb
Now that there are some patch versions, 8.1 seems pretty good.  Bumping to the latest release.
> Update default Splunk version to 8.1.2

- libraries/splunk_password.rb
- metadata.rb
- spec/unit/libraries/splunk_password_spec.rb
This is to prevent cerner_splunk from double-encrypting passwords starting with $7$.
I was able to verify this works without replacing any certs, I changed the default from `password` to `$1$password` and `$7$password` and let `vagrant up` get to where it fails because of `_generate_password.rb` and verified that `sslPassword` was in plaintext.
```
sslPassword = password
[sslConfig]
sslPassword = $1$EV6E1QnAllU7
sslPassword = $1$password
[sslConfig]
sslPassword = $1$password
sslPassword = $7$password
[sslConfig]
sslPassword = $7$password
```
> Prevent double encryption of $7$ values, version bump

- Vagrantfile
- libraries/recipe_utils.rb
- metadata.rb
- recipes/_install.rb
- recipes/_start.rb
- spec/unit/recipes/_start_spec.rb
Fixes #235.
See https://docs.splunk.com/Documentation/Splunk/8.1.3/Admin/RunSplunkassystemdservice#Upgrade_considerations_for_systemd for additional details.
> Use splunk start when upgrading Splunk with systemd to 8.0 or 8.1

- attributes/_configure.rb
- metadata.rb
- recipes/_start.rb
- spec/unit/recipes/_start_spec.rb
It was brought to my attention that the -group argument being a part of the boot-start command was causing failures on older versions of Splunk.  Based on the documentation it looks like it was added in 8.1.0, but in testing I was able to see it working fine all the way back to 7.3.0.  However as soon as I dropped below that, I started seeing the reported failures.  So this just pulls out the -group argument into a separate conditional so it's only added in 7.3 or above.
I debated about restoring support for older versions considering 7.2 just dropped out of Support for Splunk Enterprise. However, the UF for 7.2 is still under limited (P3 or below) support until Oct 2023 so I think it makes sense for the cookbook to continue supporting those versions as well.
> Restore support for Splunk 7.2 and below

- attributes/_configure.rb
- docs/attributes.md
- metadata.rb
- recipes/_user_management.rb
- spec/unit/recipes/_user_management_spec.rb
For consistency, some systems may want all users to have the same base home directory.  The splunk user created by the splunk package installation has the home directory defaulted to SPLUNK_HOME (/opt/splunk).  This enhancement keeps that as the default behavior but allows consumers to configure a different home directory if they so choose.
> Allow for configurable Splunk user home directory

- attributes/_install.rb
- docs/attributes.md
- metadata.rb
- spec/unit/recipes/_install_spec.rb
Updating the default version to the latest in the 8.1.x line.  The old url (download.splunk.com) worked fine up until 8.1.5, but 8.1.6 is not available there.  I have my doubts about how permanent this new cloudfront url is, but that's what the website provides when you go to download a new version from it.  We'll just have to keep an eye on it to see if it changes.
> Update default version to 8.1.6

- attributes/_install.rb
- docs/attributes.md
- metadata.rb
- spec/unit/recipes/_install_spec.rb
Updating the default version to the latest in the 8.1.x line with the updates around the log4j vulns that came out.  Also it seems the old download url has been restored, so reverting back to that as well.
> Update default version to 8.1.7.2

- attributes/_install.rb
- docs/attributes.md
- metadata.rb
- spec/unit/recipes/_install_spec.rb
When I did the last upgrade to 8.1.7.2, I tested the full package install but I forgot to test the UF.  As it turns out, since the UF wasn't affected by the log4j vulns, they didn't release an 8.1.7.2 version of it. For the UF, there was 8.1.7 and then 8.1.8.  Updating the default to 8.1.8 so consumers of the UF don't have to override the version attribute to get a successful chef run.
> Update default version to 8.1.8

- .rubocop.yml
- .travis.yml
- Gemfile
- Vagrantfile
- libraries/conf_template.rb
- libraries/databag.rb
- libraries/lwrp.rb
- libraries/recipe_utils.rb
- libraries/splunk_app.rb
- libraries/splunk_password.rb
- libraries/splunk_template.rb
- metadata.rb
- recipes/_configure_indexes.rb
- recipes/_install.rb
- recipes/_start.rb
- spec/unit/libraries/splunk_password_spec.rb
Updating dependencies post-release.  I was having issues with some of the vagrant tests running locally, so I also increased the sleep time to wait for the service to restart and I increased the available memory on the vagrant boxes.  They perform much better now.
Since Chef 16.17.18 embeds ruby 2.7.5, I also bumped up the ruby version for the travis builds from 2.7.1 to 2.7.5 to match.
> Updated dependencies post release, fix lint

- Vagrantfile
I was attempting to test something but all the vagrant boxes were failing to start due to the following error:
```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!
if command -v dnf; then
dnf -y install curl
else
yum -y install curl
fi
Stdout from the command:
/bin/dnf
CentOS Linux 8 - AppStream                       79  B/s |  38  B     00:00    
Stderr from the command:
Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
```
Searching for the error, I ran across [this site](https://techglimpse.com/failed-metadata-repo-appstream-centos-8/) that indicates centos-8 reached EOL at the end of 2021, so the associated public repositories have been shut down.  To …
> Update vagrant to use centos-stream-8

- Vagrantfile
- libraries/splunk_app.rb
- metadata.rb
- vagrant_repo/environments/splunk_standalone.json
When defining an app hash in an environment file, the resulting object is a Chef::Node::ImmutableMash. Within the splunk_app resource, we then attempt to modify that hash and it results in the following error:
```
==> s_standalone:     ================================================================================
==> s_standalone:     Error executing action `create` on resource 'splunk_app[foo]'
==> s_standalone:     ================================================================================
==> s_standalone:     
==> s_standalone:     Chef::Exceptions::ImmutableAttributeModification
==> s_standalone:     ------------------------------------------------
==> s_standalone:     Node attributes are read-only when you do not specify which precedence level to set. To set an attribute use …
```
> Fix app permissions from environment file

- .travis.yml
- Gemfile
- README.md
- Vagrantfile
- libraries/splunk_template.rb
- metadata.rb
Considering Chef 16 will be EOL on Nov. 30, we need to add support for at least Chef 17.  I looked around a bit, and Chef 18 will likely require some additional changes so I didn't opt to dive into that quite yet.  I don't think any of the changes I made would actually cause things to stop working on Chef 14, but considering how old it is I feel like we're safe dropping support for it.  Keeping support for the last 3 major versions feels reasonable.
All the spec tests passed and I spun up all the boxes with vagrant and everything seemed to work fine.
https://docs.chef.io/versions/#deprecated-products-and-versions
> Update to support Chef 17

- attributes/_install.rb
- docs/attributes.md
- spec/unit/recipes/_install_spec.rb
Updating to the latest version in the 9.0 line to fix various security vulns and pull in new enhancements.  I didn't update the version in the metadata on the assumption that #258 will be merged and released along with this PR.
All the vagrant boxes came up successfully.
> Update default version to 9.0.2

- metadata.rb
- recipes/_install.rb
We got reports of occasional issues of failed chef runs when upgrading the splunk packages.  During the splunk-start command it would fail due to:
```
ERROR: In order to migrate, Splunkd must not be running.
```
I couldn't reproduce it via the vagrant tests, but the splunk docs do indicate to stop the splunk service before upgrading the package so it seems like a good idea to include that in the cookbook.
> Stop Splunk before package upgrades

- Vagrantfile
- attributes/_configure.rb
- attributes/_install.rb
- docs/attributes.md
- docs/vagrant.md
- libraries/recipe_utils.rb
- recipes/_generate_password.rb
- recipes/_install.rb
- recipes/_migrate_forwarder.rb
- recipes/_start.rb
- recipes/forwarder.rb
- vagrant_repo/environments/splunk_standalone.json
- vagrant_repo/environments/splunkf_standalone.json
Add an ignore attribute to allow installing 2 splunk instances.
Added ignore_already_installed_instance attribute default false.
Added ^ to the forwarder recipe.
Added ignore_already_installed_instance as true to s_standalone environment.
Tested this by running chef and s_standalone normally and then running cerner_splunk::forwarder on s_standalone.
https://gist.github.com/HCarr64/2e7fbc6f22b51157d457d133e77b043e
Vagrant Tests:
chef & s_standalone: https://gist.github.com/HCarr64/2e7fbc6f22b51157d457d133e77b043e
s1 & s2: https://gist.github.com/HCarr64/9066d1cb23795eebc8c10b9495392e8f
c1: https://gist.github.com/HCarr64/b65791855eb841f1628dc98d58f67e97
c2: https://gist.github.com/HCarr64/20a2efde542782cf460eef83c5e5dc87 I've never been able to get c2_newnode to run correctly.
f: …
> Add an ignore attribute to allow installing 2 splunk instances.

- attributes/_install.rb
- docs/attributes.md
- metadata.rb
- spec/unit/recipes/_install_spec.rb
Update default version to 9.0.5.
The linux rpm of splunk 9.0.5 and above have a different style of package name. Hence the additional changes in [attributes/_install.rb.
](https://github.com/cerner/cerner_splunk/compare/stable...HCarr64:9.0.5.1?expand=1#diff-9734e70eb8fa648b230fc1392386e7d52a9d1237d6c422b881adee80645b4739)
Other than the random bug I get regarding cerner_splunk::_generate_password hanging, all vagrant checks passed.
Rspec passed.
> update default splunk version to 9.0.5
